name: Deploy to Workshop

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'IkarusHD/ICF-3'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project

      - name: Create Commit Version File
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/project/data_static/icf
          echo "${{ github.sha }}" > ${{ github.workspace }}/project/data_static/icf/icf-3-version.txt

      - name: Upload to Workshop
        uses: IMR-Servers/gmod-upload@master
        with:
          id: 3248769144
          changelog: "${{ github.event.head_commit.message }}"
          title: "[ICF-3] Improved Combat Framework"
          type: "tool"
          tag1: "build"
          tag2: "fun"
          tag3: "realism"
        env:
          STEAM_USERNAME: ${{ secrets.ICF_STEAM_ACCOUNT }}
          STEAM_PASSWORD: ${{ secrets.ICF_STEAM_PASSWORD }}
